version: 2
jobs:
  build:
    docker:
      - image: robmotron/circleci-gdal-go

    working_directory: /go/src/github.com/Rob-Fletcher/go-gdal
    steps:
      - checkout
      - run: go get -v -t -d ./...
      - run: go build .
      - run: go test -v ./...